@adminCookie = yoia=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZThhZjZhNTc0YjQ1ZTdkMjQ3Y2U0N2EiLCJ1c2VyVHlwZSI6ImFkbWluIiwiaWF0IjoxNTg2ODAzMDEzLCJleHAiOjE1ODkzOTUwMTN9.W1X3Fu_5CJ96laikaVrRVjHxesW0gi1m9V7ajTScoks
@userCookie = yoia=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZTkyYzZlM2RkODNmYTA1NzQ3Y2Q4ZTQiLCJ1c2VybmFtZSI6Im9ta2Fyc3RoYSIsInVzZXJUeXBlIjoidXNlciIsImlhdCI6MTU4NjkwMTM1NiwiZXhwIjoxNTg5NDkzMzU2fQ.piP7nfp23DSwNFzaLJQhyHFnhkYLtvedncgCBCAmTF0


###
POST http://localhost:6262/api/v1/users/login
content-type: application/json

{
  "identifier":"omkarstha",
  "password":"hellohello"
}


###
PATCH http://localhost:6262/api/v1/users/password
Cookie: {{userCookie}}
content-type: application/json

{
  "oldPassword":"hellohello",
  "newPassword":"hellohi"
}


###
PUT http://localhost:6262/api/v1/users/forgot
content-type: application/json

{
  "username": "",
  "email": "",
  "fullName": ""
}
# fullName is optional


###
PATCH http://localhost:6262/api/v1/users/resetpassword
content-type: application/json

{
  "resetKey": "",
  "password": ""
}
